baseURL = "https://vibhasgoyal.com/"
languageCode = "en-us"
title = "Vigo's Blog"
theme = "hyde"
paginate = 5

enableEmoji = true
googleAnalytics = "UA-64881400-2"
disqusShortname = "vibhasgoyal"

    hidden = "true"

# sectionPagesMenu = "main"

[params]
  description = "Build the future. Technology, Business, Design and Psychology "
  addThis = "ra-50594cfb1c07b16f"

[[params.social]]
  name = "github"
  url = "https://github.com/vibhas77"

  [params.style]
     darkestColor = "#315659"
     darkColor = "#253031"
     primaryColor = "#0f3b3e"
     lightColor = "#97e3a1"
     lightestColor = "#fff"
